all:
  hosts:
    Bastion-Host:
      ansible_host: "{{ lookup('pipe', 'cd ../terraform/bastion-host && terraform output -raw public_ip') }}"
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa