- hosts: Bastion-Host
  tasks:
    - name: Editar arquivo zabbix_server.conf
      lineinfile:
        path: /etc/zabbix/zabbix_server.conf
        regexp: '^# DBPassword='
        line: 'DBPassword=zabbix'
        state: present
      become: true