- name: Instalacao Zabbix Agent 2 - Ubuntu
  hosts: Bastion-Host
  gather_facts: false
  vars_files:
    - variables.yaml
  become: true
  tasks:
    - name: Baixando a chave pública do Zabbix
      apt_key:
        url: "https://repo.zabbix.com/zabbix-official-repo.key"
        state: present

    - name: Baixando repositorio
      get_url:
        url: https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_7.0-2+ubuntu24.04_all.deb
        dest: /tmp/zabbix-release_7.0-2+ubuntu24.04_all.deb
    - name: Instalar o pacote do Zabbix
      apt:
        deb: /tmp/zabbix-release_7.0-2+ubuntu24.04_all.deb

    - name: Atualizar cache de pacotes
      apt:
        update_cache: yes

    - name: Upgrade dos pacotes
      apt:
        upgrade: dist
      become: true    

    - name: Fazendo instalacao
      apt:
        name:
          - zabbix-server-mysql
          - zabbix-frontend-php
          - zabbix-apache-conf
          - zabbix-sql-scripts
          - zabbix-agent
          - mysql-server
        state: present

    - name: Criar banco de dados Zabbix
      command: >
        mysql -e "CREATE DATABASE IF NOT EXISTS zabbix CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;"
      become: yes

    - name: Criar usuário Zabbix
      command: >
        mysql -e "CREATE USER IF NOT EXISTS 'zabbix'@'localhost' IDENTIFIED BY 'zabbix';"
      become: yes

    - name: Conceder permissões ao usuário Zabbix
      command: >
        mysql -e "GRANT ALL PRIVILEGES ON zabbix.* TO 'zabbix'@'localhost';"
      become: yes

    - name: Definir log_bin_trust_function_creators
      command: >
        mysql -e "SET GLOBAL log_bin_trust_function_creators = 1;"
      become: yes

    - name: Importar o esquema do banco de dados Zabbix
      shell: |
        zcat /usr/share/zabbix-sql-scripts/mysql/server.sql.gz | mysql --default-character-set=utf8mb4 -uzabbix -pzabbix zabbix
        
    - name: Editar arquivo zabbix_server.conf
      lineinfile:
        path: /etc/zabbix/zabbix_server.conf
        regexp: '^# DBPassword='
        line: 'DBPassword=zabbix'
        state: present
      become: true
    
    - name: Reiniciar Serviços
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: restarted
      loop:
        - zabbix-server
        - zabbix-agent
        - apache2
    
    - name: Instalar dependências do Grafana
      apt:
        name:
          - adduser
          - libfontconfig1
          - musl
        state: present
      become: yes

    - name: Baixar o pacote do Grafana Enterprise
      get_url:
        url: https://dl.grafana.com/enterprise/release/grafana-enterprise_11.2.0_amd64.deb
        dest: /tmp/grafana-enterprise_11.2.0_amd64.deb

    - name: Instalar o Grafana Enterprise
      apt:
        deb: /tmp/grafana-enterprise_11.2.0_amd64.deb
      become: yes
  
    - name: Recarregar o daemon do systemd
      command: /bin/systemctl daemon-reload
      become: yes

    - name: Habilitar o serviço do Grafana
      systemd:
        name: grafana-server
        enabled: yes
      become: yes

    - name: Iniciar o serviço do Grafana
      systemd:
        name: grafana-server
        state: started
      become: yes    